name = "incident-webhook-api"
main = "src/index.ts"
compatibility_date = "2024-01-01"

[vars]
AWS_REGION = "us-east-1"
FIREBASE_PROJECT_ID = "rpfireforce"
FIREBASE_CLIENT_EMAIL = "firebase-adminsdk-fbsvc@rpfireforce.iam.gserviceaccount.com"
FIREBASE_PRIVATE_KEY = "-----BEGIN PRIVATE KEY-----\nMIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQDIUFQI6hpL715r\nL71TCGce/2AB8I5S77EPpI0xy6OLZC7/cjiNSGMtcBRzNmHs7MCuBnd9t0mnbXRL\nEw2S/vjNSkRJIfVGRx9qcQd5pjJLScrEORtlyzOHwjYOyN8bEx50p+zlIp2lA0bA\nmlwZrmaHsn3eZtQil7dizXyGs3x2EAcxpBoeYRz5j85OvgzP4V1AjVawpfLq/EwD\ndWaUMFOSdro7jU17wKyHsNsxhYfl9nzrvFMqKFu+i01l6nnFt15AUY9u081y4Afn\n1duHSQGBL1CFT/2vydGfyP1ZhUJl08aYwIeIrRTNyttVFEHWB71q574cMQELI3y3\nH/rho68NAgMBAAECggEABR96/Ih4MPknl9gucdK8X7HBk9PZa51mnFBCxUNXvA6e\nr6GY1e8VjG99GsQgeHfpmw+YjRpzA7CJNJcNJ4ygLIT/oYm7EPTJPv298jMn1fMY\nAI5aEGPy1VdfkUhSajiTl3XRcLvZ/qW+5QgfDT6LO3ipyoT10HuUqEVojOSkPoHI\n0MORWPS0FXbpNQDPWUog2HDbSf1EPf6fQdYw/MZt8qNsj23OhDot3VuqdXHXUc/v\nrH/7xW6QoWBfvY7Yrr1/WLvx+pNaEhcgPqWE6AhATInhm8r/C1kC5mzwyT10JYHW\n6Wyyr2HZsy/BfpuhgbpKQ9JEPwJh+9y59SdjvDkmpQKBgQD0hg+5XRS/k3l3fBN3\nJB9DoTOmzyi1v/Q+wMDhDLslyFzpy4h7dPNuK+lcnOQOR1PNLgvZHE53foGyOxgY\nwNw8boz2sXN7cY4eRAyDM/V8ZrkSme/1o4YDJhsiANDK2UJDNtjKWVmoPYx/1cQ8\ndp8aiMxLH8jcC/QSBZNCsHj6XwKBgQDRtxZeCXOVkPOQwDlsNWlv1OGfOnMb7cqA\nk2uYlar/jjaKOqTXRRvuL+QDw4C25GIPcKbJAsn0svbJrc7GFR2g6ozLZX0MEVPH\nEqPFTxTDnlfPnDiKCx4nZfkDLt/FbD74uhf8p8fk0R1cCe+1zD5bcO6FPpIQk3eQ\nSPSf+uEmEwKBgQDPZkJCA/xMPebh/KB6Bm5qK3mm+8DY37Zn34/5kpXOBzMfrl3V\n8S1kfeRShFQ+9CrVNkAgZ4z6d5fEN7FJlZN3woDX4U1FH9zeOPOv+Us3t900NNM+\nMvPBCforjiuKUlqMriGVB9IvC/12lDb83dQ3al51PcFdOtpKyuXLw+jo2wKBgQDN\n4bNowFijxfkH6160V79aFaEmo8gr7Ae4sIGZ+50zZBcxHx+DYwpnjMaJ112+r3mB\ndPOYNU+1Fhjnp+VuW36J4po0eD8KINyhfDAhXWCiJwpH/DMZeo6w2RBcyqDOfVVY\n88DmvoSko5LyL6MQVCIHvVe8oc/dzBg+IxFdGXv91wKBgH5sYIx070500pEvNkR4\nynFfcRoTpgPTDxu+P/JraEEZ35RJbvw5Y6EHuEuMiDBnU8K1doOFUi4LO1YN5II5\njwhUyEhb240xJSxD6iojUh8MItFU1UEdrpuvTDbnjZRREIt7nWvxIQSUgarcwo4l\nG81p0duel3Rb3tDIcL63xHbD\n-----END PRIVATE KEY-----\n"
SENDER_EMAIL = "noreply@fireforce.workers.dev"

[[d1_databases]]
binding = "DB"
database_name = "incident-management"
database_id = "c3c21ca1-204d-4db3-ab18-2cf69ec7418c"

# Add email routing
send_email = [
	{type = "send_email", name = "EMAIL"}
]
